static struct
{
    String type;
    String subtype;
    String prefix;
}
typeSubtypePrefix[] =
{
#if 1
    // Factory presets
    { "Keys", "Evolving Keys" , "KEY" },
    { "Bass", "Plucked Bass" , "BASS" },
    { "Pad", "Evolving Pad" , "PAD" },
    { "Keys", "Classic Synth Keys" , "KEY" },
    { "Bass", "Bass Line" , "BASS" },
    { "Sequence", "Melodic Sequence" , "BPM SEQ" },
    { "Sound Effects", "Noise" , "SFX" },
    { "Pad", "Atmosphere" , "ATMO" },
    { "Pad", "Classic Synth Pad" , "PAD" },
    { "Bass", "Hard Bass" , "BASS" },
    { "Sequence", "Arpeggio" , "BPM ARP" },
    { "Synth Lead", "Soft Lead" , "LEAD" },
    { "Synth Lead", "Hard Lead" , "LEAD" },
    { "Sound Effects", "Machines" , "SFX" },
    { "Keys", "Lofi Keys" , "KEY" },
    { "Sound Effects", "Ambient SFX" , "AMB" },
    { "Synth Lead", "Poly Lead" , "LEAD" },
    { "Keys", "Plucked Keys" , "PLUCK" },
    { "Sound Effects", "Nature Sounds" , "AMB" },
    { "Sequence", "Noise Sequence" , "BPM SEQ" },
    { "Synth Lead", "Solo Lead" , "LEAD" },
    { "Sound Effects", "Sweeps" , "SWEEP" },
    { "Pad", "Bright Pad" , "PAD" },
    { "Brass & Winds", "Synth Brass" , "BRASS" },
    { "Organ", "Synth Organ" , "ORGAN" },
    { "Bass", "Sub Bass" , "BASS" },
    { "Strings", "Bowed Strings" , "STRING" },
    { "Vocal", "Synth Choir" , "CHOIR" },
    { "Strings", "String Ensemble" , "STRING" },
    { "Sequence", "Rhythmic Sequence" , "BPM SEQ" },
    { "Drums", "Clap" , "DRUM" },
    { "Drums", "Tom" , "DRUM" },
    { "Template", "" , "TEMPLATE" },
    { "Strings", "Plucked Strings" , "STRING" },
    { "Brass & Winds", "Orchestral Brass" , "BRASS" },
    { "Keys", "Percussive Keys" , "KEY" },
    { "Keys", "Bells" , "BELL" },
    { "Drums", "Kick" , "DRUM" },
    { "Strings", "Guitar" , "GTR" },
    { "Pad", "Choir" , "CHOIR" },
    { "Synth Lead", "Plucked Lead" , "LEAD" },
    { "Brass & Winds", "Woodwind" , "WIND" },
    { "Sound Effects", "Soundtrack" , "SFX" },
    { "Synth Lead", "Big Lead" , "LEAD" },
    { "Keys", "Mallets" , "PERC" },
    { "Synth Lead", "Dirty Lead" , "LEAD" },
    { "Drums", "Snare" , "DRUM" },
    { "Drums", "Percussion" , "PERC" },
    { "Synth Lead", "Percussive Lead" , "LEAD" },
    { "Sound Effects", "Creative SFX" , "SFX" },
    { "Sound Effects", "Hit" , "HIT" },
    { "Drums", "Creative Drums" , "DRUM" },
    { "Piano", "Grand Piano" , "KEY" },
    { "Pad", "Strings Pad" , "PAD" },
    { "Piano", "Upright Piano" , "KEY" },
    { "Piano", "Creative Piano" , "KEY" },
    { "Electric Piano", "Creative EP" , "KEY" },
    { "Drums", "Drum Loop" , "BPM DRUM" },
    { "Brass & Winds", "Creative Brass" , "BRASS" },
    { "Lead", "Dirty Lead" , "LEAD" },
    { "Organ", "Tonewheel Organ" , "ORGAN" },
    { "Drums", "Cymbal" , "DRUM" },
    { "Lead", "Percussive Lead" , "LEAD" },
    { "Lead", "Soft Lead" , "LEAD" },
    { "Lead", "Solo Lead" , "LEAD" },
    { "Lead", "Big Lead" , "LEAD" },
    { "Lead", "Synced Lead" , "LEAD" },
    { "Lead", "Hard Lead" , "LEAD" },
    { "Vocal", "Real Choir" , "CHOIR" },
    { "Bass", "Soft Bass" , "BASS" },
    { "Brass & Winds", "Winds Hybrid" , "WIND" },
    { "Lead", "Plucked Lead" , "PLUCK" },
    { "Piano", "Hybrid" , "KEY" },
    { "Lead", "Poly Lead" , "LEAD" },
    { "Vocal", "Vocoder" , "VOX" },
    { "Brass & Winds", "Winds Acoustic" , "WIND" },
    { "Electric Piano", "Digital Piano" , "KEY" },
#endif

#if 0
    // SabrePigs v1
    { "Custom", "Ambient Pad" , "AMB" },
    { "Custom", "Polyphonic Sequence" , "BPM SEQ" },
    { "Custom", "Vocal FX" , "VOX" },
    { "Electric Piano", "Classic EP" , "KEY" },
    { "Pad", "Ambient Pad" , "AMB" },
    { "Custom", "Transition" , "SFX" },
#endif

#if 0
    // Tom Wolfe's SynthVault
    { "Keys", "Hard Bass" , "BASS" },
    { "Pad", "Ambient Pad" , "PAD" },
    { "Pad", "Textural Pad" , "PAD" },
    { "Custom", "Ambient Pad" , "PAD" },
    { "Pad", "Granular Pad" , "PAD" },
    { "Pad", "Sampled Texture" , "TEXT" },
    { "Bass", "Bass Sequence" , "BPM SEQ" },
    { "Bass", "Ambient Pad" , "AMB" },
    { "Sequence", "Cinematic Sequence" , "BPM SEQ" },
    { "Electric Piano", "Classic EP" , "KEY" },
    { "Sequence", "Synth Sequence" , "BPM SEQ" },
    { "Sound Effects", "Ambient Pad" , "AMB" },
    { "Sequence", "Bass Sequence" , "BPM SEQ" },
    { "Bass", "Digital Bass" , "BASS" },
    { "Keys", "Textural Keys" , "KEY" },
#endif

#if 0
    // Celestial Resonance
    { "Pad", "Ambient Pad" , "PAD" },
    { "Pad", "Ambient SFX" , "SFX" },
    { "Keys", "Sc-Fi Keys" , "KEY" },
    { "Pad", "Drone" , "PAD" },
    { "Keys", "Sampled Keys" , "KEY" },
    { "Lead", "Classic Synth Keys" , "LEAD" },
    { "Organ", "Space Organ" , "ORGAN" },
    { "Pad", "Soundscape" , "PAD" },
#endif

#if 1
    // Mystic Moonlight
    { "Sequence", "Sequence" , "BPM SEQ" },
    { "Sequence", "Synth Sequence" , "BPM SEQ" },
    { "Lead", "Leads" , "LEAD" },
    { "Sequence", "Psytrance Sequence" , "BPM SEQ" },
    { "Sequence", "Pulse" , "BPM SEQ" },
    { "Bass", "Pulse" , "BASS" },
    { "Keys", "Gritty Keys" , "KEY" },
    { "Pad", "Pad" , "PAD" },
    { "Pad", "Distorted Texture" , "TEXT" },
    { "Pad", "Sweeping Texture" , "SWEEP" },
    { "Pad", "Soundscape" , "ATMO" },
    { "Pad", "Textural Pad" , "TEXT" },
    { "Pad", "Dark Texture" , "TEXT" },
    { "Sequence", "Acid Sequence" , "BPM SEQ" },
    { "Sequence", "Bass Sequence" , "BPM SEQ" },
    { "Pad", "Utility FX" , "PAD" },
    { "Sound Effects", "Riser" , "RISER" },
    { "Bass", "Bass" , "BASS" },
#endif
};
